## rocketmq
apiVersion: v1
kind: Service
metadata:
  name: rocketmq
  namespace: aispring
  labels:
    app: rocketmq
spec:
  type: NodePort
  ports:
    - name: rocketmq-nameserver
      port: 9876
      nodePort: 9876
      targetPort: 9876
    - name: rocketmq-broker
      port: 10911
      nodePort: 10911
      targetPort: 10911
  selector:
    app: rocketmq

---
## dashboard
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-dashboard
  namespace: aispring
  labels:
    app: rocketmq-dashboard
spec:
  type: NodePort
  ports:
    - name: rocketmq-dashboard
      port: 8080
      nodePort: 9880
      targetPort: 8080
  selector:
    app: rocketmq-dashboard