apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq
  namespace: aispring
  labels:
    app: rocketmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq
  template:
    metadata:
      labels:
        app: rocketmq
    spec:      
      containers:
        - name: rocketmq
          image: foxiswho/rocketmq:4.8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT
              value: -Duser.home=/home/rocketmq
            - name: JAVA_OPT_EXT
              value:  -Xmn256m
          command: ["sh","-c","mqnamesrv"]
          ports:
            - containerPort: 9876
          volumeMounts:
            - name: rocketmq-logs
              mountPath: /home/rocketmq/logs
            - name: rocketmq-store
              mountPath: /home/rocketmq/store
        - name: rmqbroker
          image: foxiswho/rocketmq:4.8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT_EXT
              value: -Duser.home=/home/rocketmq -Xms1024M -Xmx1024M -Xmn256m
          command: [ "sh","-c","mqbroker -c /home/rocketmq/config/broker.conf" ]
          ports:
            - containerPort: 10909
            - containerPort: 10911
            - containerPort: 10912
          volumeMounts:
            - name: rocketmq-logs
              mountPath: /home/rocketmq/logs
            - name: rocketmq-store
              mountPath: /home/rocketmq/store
            - name: rocketmq-conf
              mountPath: /home/rocketmq/config
      volumes:
        - name: rocketmq-logs
          hostPath:
            path: /data/k8s/rocketmq/logs
        - name: rocketmq-store
          hostPath:
            path: /data/k8s/rocketmq/store
        - name: rocketmq-config
          configMap:
            name: rocketmq-config