kind: ConfigMap
apiVersion: v1
metadata:
  name: rocketmq-config
  namespace: aispring
  labels:
    app: rocketmq
data:
  broker.conf: |-
    brokerClusterName = DefaultCluster
    brokerName = broker-a
    brokerId = 0
    namesrvAddr=rocketmq:9876;
    deleteWhen = 04
    fileReservedTime = 48
    brokerRole = ASYNC_MASTER
    flushDiskType = ASYNC_FLUSH
    # set `brokerIP1` if you want to set physical IP as broker IP.
    # brokerIP1=10.10.101.80 #change you own physical IP Address
    brokerIP1=192.168.66.231