## nameserver
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-nameserver
  namespace: aispring
  labels:
    app: rocketmq-nameserver
spec:
  type: NodePort
  ports:
    - name: rocketmq-nameserver
      port: 9876
      nodePort: 9876
      targetPort: 9876
  selector:
    app: rocketmq-nameserver
---

## broker
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-broker
  namespace: aispring
  labels:
    app: rocketmq-broker
spec:
  type: NodePort
  ports:
    - name: rocketmq-broker1
      port: 10909
      nodePort: 10909
      targetPort: 10909
    - name: rocketmq-broker12
      port: 10911
      nodePort: 10911
      targetPort: 10911
  selector:
    app: rocketmq-broker

---
## dashboard
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-dashboard
  namespace: aispring
  labels:
    app: rocketmq-dashboard
spec:
  type: NodePort
  ports:
    - name: rocketmq-dashboard
      port: 8080
      nodePort: 9880
      targetPort: 8080
  selector:
    app: rocketmq-dashboard