## Service
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-nameserver
  namespace: aispring
  labels:
    app: rocketmq
spec:
  type: NodePort
  ports:
    - name: rocketmq-nameserver
      port: 9876
      nodePort: 9876
      targetPort: 9876
  selector:
    app: rocketmq-nameserver
  
## Service
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-broker
  namespace: aispring
  labels:
    app: rocketmq
spec:
  type: NodePort
  ports:
    - name: rocketmq-broker1
      port: 10909
      nodePort: 10909
      targetPort: 10909
    - name: rocketmq-broker12
      port: 10911
      nodePort: 10911
      targetPort: 10911
  selector:
    app: rocketmq-broker