apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: aispring
  labels:
    app: sonarqube
spec:
  ports:
    - name: http
      port: 9000
      nodePort: 9000
      targetPort: http
  type: NodePort
  selector:
    app: sonarqube
