apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aispring
  name: xxl-job
  labels: 
    app: xxl-job
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: xxl-job
  template: 
    metadata: 
      labels: 
        app: xxl-job
    spec: 
      containers:
        - name: xxl-job
          image: xuxueli/xxl-job-admin:2.3.0
          imagePullPolicy: IfNotPresent
          env: 
            - name: TZ
              value: Asia/Shanghai
            - name: PARAMS
              value: --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true --server.context-path=/ --spring.datasource.username=root --spring.datasource.password=123456
          ports: 
            - name: http
              containerPort: 8080 
          livenessProbe: 
            httpGet: 
              path: /
              port: 8080 
            initialDelaySeconds: 180
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
## Service
apiVersion: v1
kind: Service
metadata:
  name: xxl-job
  namespace: aispring
  labels:
    app: xxl-job
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: xxl-job
# web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxl-job
  namespace: aispring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - xxl-job.aispring.cloud
        - "*.aispring.cloud"
      secretName: aispring-https-certs
  rules:
    - host: xxl-job.aispring.cloud
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: xxl-job
                port: 
                  name: http