apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-config
  namespace: aispring
data:
  mysql.db.name: "nacos"
  mysql.port: "3306"
  mysql.user: "root"
  mysql.password: "123456"
  mysql.host: "mysql"