apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: aispring
data:
  custom.cnf: |
    [mysqld]
    default_storage_engine=innodb
    skip_external_locking
    lower_case_table_names=1
    skip_host_cache
    skip_name_resolve
    skip-log-bin
    max_connections = 1024
