apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: aispring
  labels:
    app: elasticsearch
spec:
  ports:
    - name: rest
      port: 9200
      nodePort: 9200
      targetPort: rest
    - name: inter-node
      port: 9300
      targetPort: inter-node
  type: NodePort
  selector:
    app: elasticsearch
