apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: aispring
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.14.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
          ports:
          - containerPort: 5601
            name: http
            protocol: TCP