apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: aispring
  labels:
    app: kibana
spec:
  ports:
    - name: http
      port: 5601
      nodePort: 5601
      targetPort: http
  type: NodePort
  selector:
    app: kibana
