apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: aispring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - prometheus.aispring.cloud
        - "*.aispring.cloud"
      secretName: aispring-https-certs
  rules:
    - host: prometheus.aispring.cloud
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: prometheus
                port: 
                  name: http