# prometheus server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: aispring
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - image: prom/prometheus
          name: prometheus
          imagePullPolicy: IfNotPresent
          command:
          - "/bin/prometheus"
          args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--storage.tsdb.retention=24h"
          ports:
          - containerPort: 9090
            protocol: TCP
            name: http
          # env:
          env:
            - name: GF_PATHS_PROVISIONING
              value: /var/lib/grafana/provisioning
            - name: TZ
              value: Asia/Shanghai
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
          - mountPath: "/prometheus"
            name: prometheus-data
          - mountPath: "/etc/prometheus"
            name: prometheus-server-config
      volumes:
        - name: prometheus-server-config
          configMap:
            name: prometheus-server-config
        - name: prometheus-data
          hostPath:
            path: /out_data/k8s/prometheus/data
---
# node export 监控宿主机
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-node-exporter
  namespace: aispring
  labels:
    app: prometheus-node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-node-exporter
  template:
    metadata:
      labels:
        app: prometheus-node-exporter
    spec:
      containers:
        - image: prom/node-exporter
          name: prometheus-node-exporter
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9100
            protocol: TCP
            name: http
          # env:
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
          - name: proc
            mountPath: /host/proc
          - name: sys
            mountPath: /host/sys
          - name: root
            mountPath: /rootfs
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
---