apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus-server-config
  name: prometheus-server-config
  namespace: aispring
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'node-monitor'
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
      scrape_interval: 5s
      static_configs:
      - targets: ['prometheus-node-exporter:9100']