apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: aispring
data:
  config.toml: |
    concurrent = 5
    check_interval = 0
    [session_server]
      session_timeout = 1800
    [[runners]]
      name = "shared token"
      url = "http://git.aispring.cloud/"
      token = "CyQ6itZy9Wpq7uzmuqdA"
      tls-ca-file = "/etc/gitlab-runner/aispring.cloud-cert/tls.crt"
      tls-key-file = "/etc/gitlab-runner/aispring.cloud-cert/tls.key"
      executor = "kubernetes"
      [runners.custom_build_dir]
      [runners.cache]
        [runners.cache.s3]
        [runners.cache.gcs]
        [runners.cache.azure]
      [runners.kubernetes]
        host = "https://192.168.66.231:6443"
        cert_file = "/etc/gitlab-runner/k8s-cert/apiserver.crt"
        key_file = "/etc/gitlab-runner/k8s-cert/apiserver.key"
        ca_file = "/etc/gitlab-runner/k8s-cert/ca.crt"
        bearer_token_overwrite_allowed = false
        bearer_token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjU2Tzg4RjdhZlFWQkpWbjFqZUJVUmVjZXI5MmthM3Y0cVAzTy1KV0h0ZFUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tYzJjbGoiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijc3MDUwZmVmLWQxNmEtNDc3OC1hNDllLTNlOWUzMjgwYTNmYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.QRCBVFB7Z7ku8a0dRVWWQMpkoWOKJkytQ-qccRlK8nKktuuOqVBxA1FcWAzyetL5RCyz3lN-VRaiOq9IY6MXnlGY9Y2JSYnGXMc1gVp0e4MihpK25IYeLAkZepo5a6gd2OO2FrlBpx_6ujyu6rZE53JBsG84HFPThD-kWXlPlT8Cm1MziMKLlfJUQCKJ1cnFRrUgQRf4V0SJ709fjwLkBA-1iDyFfnHweGwqejhcq3tA7i6TcyXws9CyEDuiNkYPtqRqbQB3_9DdH68F3sYsLdI5J5wiRdWUqB0nl5Gb3YOCqIzVG-nkGDnnjX4xFLtG_zJoq98iN5ZmQjefgrgRlw"
        image = "busybox"
        namespace = "gitlab-runner"
        namespace_overwrite_allowed = ""
        privileged = false
        service_account_overwrite_allowed = ""
        pod_annotations_overwrite_allowed = ""
        [runners.kubernetes.affinity]
        [runners.kubernetes.pod_security_context]
        [[runners.kubernetes.volumes.host_path]]
          name = "m2"
          mount_path = "/root/.m2"
          host_path = "/home/spring/data/k8s/gitlab-runner/data/.m2"
        [[runners.kubernetes.volumes.host_path]]
          name = "npm"
          mount_path = "/root/.npm"
          host_path = "/home/spring/data/k8s/gitlab-runner/data/.npm"
        [[runners.kubernetes.volumes.host_path]]
          name = "m2"
          mount_path = "/root/.gradle"
          host_path = "/home/spring/data/k8s/gitlab-runner/data/.gradle"
        [[runners.kubernetes.volumes.host_path]]
          name = "m2"
          mount_path = "/opt/app"
          host_path = "/home/spring/data/k8s/gitlab-runner/data/app"
        [[runners.kubernetes.volumes.host_path]]
          name = "m2"
          mount_path = "/var/run/docker.sock"
          host_path = "/var/run/docker.sock"
        [runners.kubernetes.dns_config]
