apiVersion: v1
kind: ReplicationController
metadata:
  namespace: aispring
  name: hadoop-resourcemanager
  labels:
    name: hadoop-resourcemanager
spec:
  replicas: 1
  selector:
    name: hadoop-resourcemanager
  template:
    metadata:
      labels:
        name: hadoop-resourcemanager
    spec:
      containers:
        - name: hadoop-resourcemanager
          image: bde2020/hadoop-resourcemanager
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
          ports:
            - containerPort: 8088
          env:
            - name: SERVICE_PRECONDITION
              value: "hadoop-namenode:9000 hadoop-namenode:9870 hadoop-datanode:9864"
            - name: HDFS_MASTER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: hadoop-conf
                  key: HDFS_MASTER_SERVICE
            - name: HDOOP_YARN_MASTER
              valueFrom:
                configMapKeyRef:
                  name: hadoop-conf
                  key: HDOOP_YARN_MASTER
      restartPolicy: Always
---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: aispring
  name: hadoop-nodemanager
  labels:
    name: hadoop-nodemanager
spec:
  replicas: 1
  selector:
    name: hadoop-nodemanager
  template:
    metadata:
      labels:
        name: hadoop-nodemanager
    spec:
      containers:
        - name: hadoop-nodemanager
          image: bde2020/hadoop-nodemanager
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
          ports:
            - containerPort: 8040
            - containerPort: 8041
            - containerPort: 8042
          env:
            - name: SERVICE_PRECONDITION
              value: "hadoop-namenode:9000 hadoop-namenode:9870 hadoop-datanode:9864 hadoop-resourcemanager:8088"
      restartPolicy: Always
---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: aispring
  name: hadoop-historyserver
  labels:
    name: hadoop-historyserver
spec:
  replicas: 1
  selector:
    name: hadoop-historyserver
  template:
    metadata:
      labels:
        name: hadoop-historyserver
    spec:
      containers:
        - name: hadoop-historyserver
          image: bde2020/hadoop-historyserver
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
          ports:
            - containerPort: 8188
          env:
            - name: SERVICE_PRECONDITION
              value: "hadoop-namenode:9000 hadoop-namenode:9870 hadoop-datanode:9864 hadoop-resourcemanager:8088"
      restartPolicy: Always
