apiVersion: v1
kind: ReplicationController
metadata:
  namespace: aispring
  name: hadoop-namenode
  labels:
    name: hdfs
spec:
  replicas: 1
  selector:
    name: hadoop-namenode
  template:
    metadata:
      labels:
        name: hadoop-namenode
    spec:
      containers:
        - name: hadoop-namenode
          image: bde2020/hadoop-namenode
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
          ports:
            - containerPort: 9820
            - containerPort: 9870
          env:
            - name: CLUSTER_NAME
              value: aispring
      restartPolicy: Always
---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: aispring
  name: hadoop-datanode
  labels:
    app: hadoop
spec:
  replicas: 1
  selector:
    name: hadoop-datanode
  template:
    metadata:
      labels:
        name: hadoop-datanode
    spec:
      containers:
        - name: hadoop-datanode
          image: bde2020/hadoop-datanode
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
          ports:
            - containerPort: 9864
          env:
            - name: SERVICE_PRECONDITION
              value: "hadoop-namenode:9870"
      restartPolicy: Always