# namenode
apiVersion: v1
kind: Service
metadata:
  namespace: aispring
  name: hadoop-namenode
spec:
  type: NodePort
  selector:
    name: hadoop-namenode
  ports:
    - name: rpc
      port: 9820
      targetPort: 9820
      nodePort: 39820
    - name: http
      port: 9870
      targetPort: 9870
      nodePort: 39870
---
# datanode
apiVersion: v1
kind: Service
metadata:
  namespace: aispring
  name: hadoop-datanode
spec:
  type: NodePort
  selector:
    name: hadoop-datanode
  ports:
    - name: http
      port: 9864
      targetPort: 9864
      nodePort: 39864
---
# resourcemanager
apiVersion: v1
kind: Service
metadata:
  namespace: aispring
  name: hadoop-resourcemanager
spec:
  type: NodePort
  selector:
    name: hadoop-resourcemanager
  ports:
    - name: http
      port: 8088
      targetPort: 8088
      nodePort: 38088
---
# nodemanager
apiVersion: v1
kind: Service
metadata:
  namespace: aispring
  name: hadoop-nodemanager
spec:
  type: NodePort
  selector:
    name: hadoop-nodemanager
  ports:
    - name: http
      port: 8042
      targetPort: 8042
      nodePort: 38042
---
# historyserver
apiVersion: v1
kind: Service
metadata:
  namespace: aispring
  name: hadoop-historyserver
spec:
  type: NodePort
  selector:
    name: hadoop-historyserver
  ports:
    - name: http
      port: 8188
      targetPort: 8188
      nodePort: 38188
---