apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hadoop-namenode
  namespace: aispring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - hadoop-namenode.local.aispring.cloud
        - "*.local.aispring.cloud"
      secretName: local-aispring-https-certs
  rules:
    - host: hadoop-namenode.local.aispring.cloud
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: hadoop-namenode
                port: 
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hadoop-datanode
  namespace: aispring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - hadoop-datanode.local.aispring.cloud
        - "*.local.aispring.cloud"
      secretName: local-aispring-https-certs
  rules:
    - host: hadoop-datanode.local.aispring.cloud
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: hadoop-datanode
                port: 
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hadoop-resourcemanager
  namespace: aispring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - hadoop-resourcemanager.local.aispring.cloud
        - "*.local.aispring.cloud"
      secretName: local-aispring-https-certs
  rules:
    - host: hadoop-resourcemanager.local.aispring.cloud
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: hadoop-resourcemanager
                port: 
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hadoop-nodemanager
  namespace: aispring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - hadoop-nodemanager.local.aispring.cloud
        - "*.local.aispring.cloud"
      secretName: local-aispring-https-certs
  rules:
    - host: hadoop-nodemanager.local.aispring.cloud
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: hadoop-nodemanager
                port: 
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hadoop-historyserver
  namespace: aispring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - hadoop-historyserver.local.aispring.cloud
        - "*.local.aispring.cloud"
      secretName: local-aispring-https-certs
  rules:
    - host: hadoop-historyserver.local.aispring.cloud
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: hadoop-historyserver
                port: 
                  name: http