## flink
apiVersion: v1
kind: Service
metadata:
  name: flink
  namespace: aispring
  labels:
    app: flink
spec:
  type: NodePort
  ports:
    - name: rpc
      port: 6123
      nodePort: 6123
      targetPort: 6123
    - name: blob
      port: 6124
      nodePort: 6124
      targetPort: 6124
    - name: ui
      port: 8081
      nodePort: 8081
      targetPort: 8081
  selector:
    app: flink